on:
  push:
    tags:
      - "v*.*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish
        uses: Jaksuhn/DynamisPublishAction@master
        with:
          plugin_id: 29
          publisher_key: ${{ secrets.PUBLISHER_KEY }}